// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANdWpjLGLEaMXaCmcQpyXON-R88QH0vCo',
    appId: '1:945084691466:web:1053b91d3205845e3c9bf3',
    messagingSenderId: '945084691466',
    projectId: 'soundplay-121103',
    authDomain: 'soundplay-121103.firebaseapp.com',
    storageBucket: 'soundplay-121103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1r4V1O6MmJDZGEzAxwrWIb0H5E18puHA',
    appId: '1:945084691466:android:86fe1c8613d82d4a3c9bf3',
    messagingSenderId: '945084691466',
    projectId: 'soundplay-121103',
    storageBucket: 'soundplay-121103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpruXB_muPqiywJvimF4XGaX43rVoe3MQ',
    appId: '1:945084691466:ios:d5127c51c793c3be3c9bf3',
    messagingSenderId: '945084691466',
    projectId: 'soundplay-121103',
    storageBucket: 'soundplay-121103.appspot.com',
    iosBundleId: 'com.example.soundPlay',
  );
}
